window.NexCreatorModules=(()=>{
 const registry=window.NEX_CREATOR_MODULES||[],q=v=>typeof v==='string'?document.querySelector(v):v,esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const getDef=v=>typeof v==='object'&&v.id?v:registry.find(x=>x.id===v||x.slug===v);const clamp=(n,a,b)=>Math.max(a,Math.min(b,Number(n)||0));
 const demo={avatar:'assets/media/photo-creator.svg',media:'assets/media/website-screenshot.svg',product:'assets/media/photo-product.svg'};
 const defaults={style:'clean-editorial',energy:'medium',duration:1.8,contentLength:'medium',title:'Creator module',caption:'Replaceable creator content.',handle:'@creator',date:'Today',avatar:demo.avatar,media:demo.media,logoSrc:'',items:[]};
 const img=(src,alt='Replaceable media')=>src?`<img src="${esc(src)}" alt="${esc(alt)}">`:`<span class="cm-placeholder">MEDIA</span>`;
 const avatar=c=>`<div class="cm-avatar">${img(c.avatar,c.title)}</div>`;const logo=c=>c.logoSrc?`<img class="cm-logo" src="${esc(c.logoSrc)}" alt="Authorized brand logo">`:`<div class="cm-logo cm-logo-fallback">NS</div>`;
 const head=c=>`<div class="cm-head">${avatar(c)}<div><strong data-fit>${esc(c.title)}</strong><small data-fit>${esc(c.handle||c.date||'')}</small></div></div>`;
 const metric=(label,value,change)=>`<article class="cm-metric"><small>${esc(label)}</small><strong data-count="${Number(value)||0}">0</strong><em class="${Number(change)<0?'negative':'positive'}">${Number(change)>0?'+':''}${Number(change||0)}%</em></article>`;
 const buttons=(items)=>`<div class="cm-link-list">${items.map((x,i)=>`<button><b>${String(i+1).padStart(2,'0')}</b><span>${esc(typeof x==='string'?x:x.text||x.label)}</span><i>↗</i></button>`).join('')}</div>`;
 function render(def,c){const items=c.items||[];switch(def.slug){
 case'social-post':return `${head(c)}<div class="cm-media">${img(c.media,c.caption)}</div><p data-fit>${esc(c.caption)}</p><div class="cm-actions"><span>♥ ${c.counts?.likes||2840}</span><span>◌ ${c.counts?.comments||184}</span><span>↗ ${c.counts?.shares||96}</span><small>${esc(c.date)}</small></div>`;
 case'thread':return `${head(c)}<h3 data-fit>${esc(c.title)}</h3><ol class="cm-thread">${items.map((x,i)=>`<li><b>${i+1}</b><span data-fit>${esc(x)}</span></li>`).join('')}</ol>`;
 case'comment-exchange':return `<h3>${esc(c.title)}</h3><div class="cm-comments">${items.map((x,i)=>`<article class="${i%2?'mine':''}"><b>${esc(x.author)}</b><p data-fit>${esc(x.text)}</p></article>`).join('')}</div>`;
 case'creator-profile':return `<div class="cm-profile-hero">${avatar(c)}<div><h2 data-fit>${esc(c.title)}</h2><b>${esc(c.handle)}</b><p data-fit>${esc(c.body||c.caption)}</p></div></div><div class="cm-profile-links"><span>VIDEOS</span><span>NEWSLETTER</span><span>WORKSHOPS</span></div>`;
 case'subscriber-counter':case'view-counter':return `<div class="cm-counter-icon" data-icon="${def.slug==='subscriber-counter'?'subscriber':'view-count'}"></div><small>${esc(c.title)}</small><strong class="cm-big-count" data-count="${Number(c.value)||0}">0</strong><em>+${Number(c.change||0)}%</em>`;
 case'engagement-summary':case'campaign-result':case'affiliate-result':return `<h3>${esc(c.title)}</h3><div class="cm-metrics">${items.map(x=>metric(x.label,x.value,x.change)).join('')}</div>`;
 case'content-calendar':return `<h3>${esc(c.title)}</h3><div class="cm-calendar">${items.map(x=>`<article><b>${esc(x.label)}</b><span data-fit>${esc(x.text)}</span></article>`).join('')}</div>`;
 case'publishing-checklist':return `<h3>${esc(c.title)}</h3><ul class="cm-checklist">${items.map(x=>`<li class="${x.done?'done':''}"><i>${x.done?'✓':'○'}</i><span>${esc(x.text)}</span></li>`).join('')}</ul>`;
 case'thumbnail-selector':return `<h3>${esc(c.title)}</h3><div class="cm-thumbs">${items.map((x,i)=>`<article class="${i==c.selected?'selected':''}"><div>${img(c.media,x)}</div><b data-fit>${esc(x)}</b><span>${i==c.selected?'SELECTED':'OPTION '+(i+1)}</span></article>`).join('')}</div>`;
 case'video-chapters':return `<h3>${esc(c.title)}</h3><ol class="cm-chapters">${items.map(x=>`<li><b>${esc(x.time)}</b><span data-fit>${esc(x.text)}</span><i></i></li>`).join('')}</ol>`;
 case'newsletter-card':return `<div class="cm-publish-icon" data-icon="newsletter"></div><small>${esc(c.handle)}</small><h2 data-fit>${esc(c.title)}</h2><p data-fit>${esc(c.caption)}</p><button>READ THE LATEST ISSUE</button>`;
 case'podcast-episode':return `<div class="cm-podcast-art">${img(c.media,c.title)}<span>▶</span></div><div><small>${esc(c.handle)}</small><h2 data-fit>${esc(c.title)}</h2><p data-fit>${esc(c.caption)}</p><div class="cm-wave">${Array.from({length:18},(_,i)=>`<i style="height:${12+(i*17)%34}px"></i>`).join('')}</div></div>`;
 case'blog-article':return `<div class="cm-article-media">${img(c.media,c.title)}</div><small>${esc(c.handle)}</small><h2 data-fit>${esc(c.title)}</h2><p data-fit>${esc(c.caption)}</p>`;
 case'community-poll':case'reaction-panel':return `<h3>${esc(c.title)}</h3><div class="cm-poll">${items.map((x,i)=>`<article><div><b>${esc(x.label)}</b><span>${x.value}%</span></div><i style="--value:${clamp(x.value,0,100)}%"></i></article>`).join('')}</div>`;
 case'question-and-answer-card':return `<div class="cm-qa"><b>Q</b><h2 data-fit>${esc(c.title)}</h2><b>A</b><p data-fit>${esc(c.caption)}</p></div>`;
 case'testimonial':case'review':return `<div class="cm-quote">“</div><p class="cm-quote-copy" data-fit>${esc(c.caption)}</p><div class="cm-proof-foot">${avatar(c)}<div><b>${esc(c.title)}</b><small>${esc(c.handle)}</small></div>${def.slug==='review'?`<strong>★ ${c.value||4.9}</strong>`:''}</div>`;
 case'user-generated-content-frame':return `${head(c)}<div class="cm-media">${img(c.media,c.caption)}</div><p data-fit>${esc(c.caption)}</p><span class="cm-ugc-label">COMMUNITY FEATURE</span>`;
 case'creator-collaboration':return `<div class="cm-collab"><div>${avatar(c)}<b>${esc(c.title.split('×')[0]||'Creator')}</b></div><span>×</span><div>${avatar({...c,avatar:c.media})}<b>${esc(c.title.split('×')[1]||'Creator')}</b></div></div><p data-fit>${esc(c.caption)}</p><small>${esc(c.handle)}</small>`;
 case'sponsorship-card':return `${logo(c)}<small>${esc(c.handle)}</small><h2 data-fit>${esc(c.title)}</h2><p data-fit>${esc(c.caption)}</p><span class="cm-sponsored">SPONSORED SEGMENT</span>`;
 case'brand-partnership':return `<div class="cm-partner-lockup"><div class="cm-creator-mark">MC</div><span>×</span>${logo(c)}</div><h2 data-fit>${esc(c.title)}</h2><p data-fit>${esc(c.caption)}</p><small>${esc(c.handle)}</small>`;
 case'link-in-bio-screen':return `${head(c)}${buttons(items)}`;
 case'call-to-follow':case'call-to-subscribe':return `<div class="cm-action-icon" data-icon="${def.slug==='call-to-follow'?'subscriber':'newsletter'}"></div><h2 data-fit>${esc(c.title)}</h2><p data-fit>${esc(c.caption)}</p><button>${def.slug==='call-to-follow'?'FOLLOW':'SUBSCRIBE'}</button><small>${esc(c.handle)}</small>`;
 default:return `<h2>${esc(c.title)}</h2><p>${esc(c.caption)}</p>`}
 }
 function mountLower(el,c){el.querySelectorAll('[data-icon]').forEach(slot=>{if(window.NexCreatorIcons){const icon=NexCreatorIcons.create('icon.creator.'+slot.dataset.icon+'.paper-01',{size:70,state:'active',treatment:'paper-cutout'});slot.append(icon)}})}
 function fitText(el){el.querySelectorAll('[data-fit]').forEach(n=>{n.style.fontSize='';n.style.overflowWrap='anywhere';let g=0;while((n.scrollWidth>n.clientWidth+2||n.scrollHeight>n.clientHeight+2)&&g<50){let s=parseFloat(getComputedStyle(n).fontSize)||14;if(s<=8)break;n.style.fontSize=(s-.4)+'px';g++}});return el}
 function create(defOrId,config={}){const def=getDef(defOrId);if(!def)throw Error('Unknown creator module '+defOrId);const c={...defaults,...JSON.parse(JSON.stringify(def.sampleConfig||{})),...config};if(c.contentLength==='short'){c.caption=String(c.caption||'').slice(0,90);c.items=(c.items||[]).slice(0,3)}if(c.contentLength==='long'){c.caption=(c.caption||'')+' '+(c.longExtra||'Additional context remains editable and safely fitted inside the component.');}
 const el=document.createElement('section');el.className=`nex-creator-module module-${def.slug}`;el.dataset.componentId=def.id;el.dataset.slug=def.slug;el.dataset.style=c.style;el.dataset.energy=c.energy;el.dataset.contentLength=c.contentLength;el.setAttribute('role','group');el.setAttribute('aria-label',def.accessibilityLabel);el.__moduleConfig=c;el.innerHTML=`<div class="cm-shell"><div class="cm-content">${render(def,c)}</div><div class="cm-grain"></div></div>`;mountLower(el,c);requestAnimationFrame(()=>fitText(el));return el}
 function animate(target,config={}){const el=q(target),d=Number(config.duration||el?.__moduleConfig?.duration||1.8),energy=config.energy||el?.dataset.energy||'medium',amp={low:.7,medium:1,high:1.3}[energy]||1,motion=config.motion||'paper-slide';if(!el)throw Error('Creator module target missing');const shell=el.querySelector('.cm-shell'),tl=NexMotion.createTimeline({defaults:{ease:'power3.out'}});if(motion==='cut-paper-pop')tl.fromTo(shell,{scale:.7,rotation:-3*amp,opacity:0},{scale:1,rotation:0,opacity:1,duration:d*.45,ease:'back.out(1.7)'},0);else if(motion==='drop-and-settle')tl.fromTo(shell,{y:-80*amp,rotation:5*amp,opacity:0},{y:0,rotation:0,opacity:1,duration:d*.48,ease:'bounce.out'},0);else if(motion==='unfold')tl.fromTo(shell,{scaleY:.08,rotationX:68,opacity:0,transformOrigin:'50% 0%'},{scaleY:1,rotationX:0,opacity:1,duration:d*.5,ease:'power3.out'},0);else tl.fromTo(shell,{x:-70*amp,y:12,opacity:0},{x:0,y:0,opacity:1,duration:d*.45,ease:'power3.out'},0);
 const pieces=[...el.querySelectorAll('.cm-content>*')];pieces.forEach((x,i)=>tl.fromTo(x,{y:18+(i%3)*6,opacity:0,scale:.97},{y:0,opacity:1,scale:1,duration:d*.26,ease:i%2?'back.out(1.4)':'power2.out'},.25+i*.075));el.querySelectorAll('[data-count]').forEach((n,i)=>{const to=Number(n.dataset.count)||0;tl.addUpdate(.35+i*.08,d*.45,p=>n.textContent=Intl.NumberFormat(undefined,{notation:to>9999?'compact':'standard',maximumFractionDigits:1}).format(Math.round(to*p)),'power3.out')});el.querySelectorAll('.cm-poll i').forEach((n,i)=>tl.fromTo(n,{scaleX:0},{scaleX:1,duration:d*.34,ease:'power3.out'},.42+i*.08));el.querySelectorAll('.cm-checklist li').forEach((n,i)=>tl.fromTo(n,{x:-24,opacity:0},{x:0,opacity:1,duration:d*.25},.35+i*.1));tl.fromTo(shell,{y:0},{y:-3*amp,duration:.8,ease:'sine.inOut',repeat:2,yoyo:true},Math.max(.9,d*.75));tl.seek(0);el.__tl=tl;return tl}
 function update(target,config={}){const el=q(target),next=create(el.dataset.componentId,{...el.__moduleConfig,...config});el.replaceWith(next);return next}
 return{registry,getDef,create,animate,update,fitText};})();