window.NexSceneRigs=(()=>{
 const registry=window.NEX_SCENE_RIGS||[],q=v=>typeof v==='string'?document.querySelector(v):v,esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const getDef=v=>typeof v==='object'&&v.id?v:registry.find(x=>x.id===v||x.slug===v); const clamp=(n,a,b)=>Math.max(a,Math.min(b,Number(n)||0));
 const defaults={style:'clean-editorial',energy:'medium',variant:'A',duration:7.5,title:'Reusable scene',subtitle:'NEXSTUDIO PAPER MOTION',body:'Configurable storytelling structure.',media:'assets/media/website-screenshot.svg',items:[],data:null,logo:''};
 const iconCollections=[window.NexIcons,window.NexCreatorIcons,window.NexAgentIcons,window.NexBusinessIcons];
 function createIcon(slug,c){for(const api of iconCollections){if(!api)continue;const d=api.getDef?.(slug)||api.registry?.find(x=>x.slug===slug||x.id.endsWith('.'+slug+'.paper-01'));if(d){try{return api.create(d,{size:88,state:'active',treatment:'paper-cutout',energy:c.energy})}catch(_){}}}return document.createTextNode('✦')}
 function typography(slug,c){try{return NexTypography.create(slug,{title:c.title,text:c.title,body:c.body,subtitle:c.subtitle,items:c.items?.map(x=>typeof x==='string'?x:(x.label||x.text))||[],style:c.style,energy:c.energy,alignment:c.variant==='B'?'center':'left',number:c.value||'86%',button:'BUILD THE STORY',emphasisWords:(c.emphasisWords||c.title.split(' ').slice(0,2))})}catch(_){const d=document.createElement('div');d.className='sr-fallback-type';d.innerHTML='<h2>'+esc(c.title)+'</h2><p>'+esc(c.body)+'</p>';return d}}
 function media(slug,c){try{return NexMediaContainers.create(slug,{title:c.title,caption:c.body,media:c.media,style:c.style,border:c.variant==='B'?'taped':'clean',cropMode:'cover',focalX:50,focalY:50})}catch(_){const d=document.createElement('div');d.className='sr-fallback-media';d.textContent='REPLACEABLE MEDIA';return d}}
 function data(slug,c,def){try{let items=c.data?.items||c.items;if(!items?.length)items=[{label:'Approved',value:72,change:12},{label:'Reusable',value:86,change:19},{label:'Ready',value:94,change:8}];let nodes=c.data?.nodes||[{id:'a',label:'INPUT',type:'source'},{id:'b',label:'COMPOSE',type:'agent'},{id:'c',label:'VALIDATE',type:'review'},{id:'d',label:'OUTPUT',type:'result'}],edges=c.data?.edges||[{from:'a',to:'b'},{from:'b',to:'c'},{from:'c',to:'d'}];return NexDataVisualisations.create(slug,{title:c.subtitle,subtitle:c.body,items,nodes,edges,style:c.style,energy:c.energy,format:slug.includes('percentage')?'percent':'compact',value:c.value||72,change:c.change||18})}catch(_){const d=document.createElement('div');d.className='sr-fallback-data';d.textContent='JSON DATA';return d}}
 function paperObject(slug,c){try{return NexPaperObjects.create(slug,{title:c.title,body:c.body,style:c.style,energy:c.energy})}catch(_){const d=document.createElement('div');d.className='sr-paper-chip';d.textContent='PAPER';return d}}
 function creatorModule(slug,c){try{return NexCreatorModules.create(slug,{title:c.title,caption:c.body,handle:'@nexstudio',media:c.media,style:c.style,energy:c.energy,items:c.items||[],value:c.value||4.9})}catch(_){return media('testimonial-card',c)}}
 function documentary(slug,c){try{return NexDocumentaryModules.create(slug,{title:c.title,caption:c.body,source:'NexStudio archive',media:c.media,style:c.style,mood:c.mood||'serious',items:c.items||[]})}catch(_){return media('document-viewer',c)}}
 function mountPart(slot,kind,slug,c,def){let el;if(kind==='typography')el=typography(slug,c);else if(kind==='icon')el=createIcon(slug,c);else if(kind==='media')el=media(slug,c);else if(kind==='data')el=data(slug,c,def);else if(kind==='object')el=paperObject(slug,c);else if(kind==='creator')el=creatorModule(slug,c);else if(kind==='documentary')el=documentary(slug,c);if(el)slot.append(el)}
 function structure(def,c){const slug=def.slug;let parts=[];
  const t=def.approvedComponents.typography,i=def.approvedComponents.icon,m=def.approvedComponents.media,d=def.approvedComponents.data;
  if(['testimonial','social-proof','comment-or-reaction','profile-introduction'].includes(slug)){const cm={testimonial:'testimonial','social-proof':'engagement-summary','comment-or-reaction':'comment-exchange','profile-introduction':'creator-profile'}[slug];parts=[['typography',t],['creator',cm],['data',d],['icon',i]]}
  else if(['news-update','documentary-evidence','photo-collage','map-or-journey','credits','closing-statement'].includes(slug)){const dm={ 'news-update':'newspaper-headline','documentary-evidence':'document-reveal','photo-collage':'photo-collage','map-or-journey':'map-journey','credits':'credits-page','closing-statement':'closing-reflection'}[slug];parts=[['typography',t],['documentary',dm],['icon',i],['data',d]]}
  else if(['chapter-opening','numbered-list','process','recap','logo-reveal'].includes(slug)){parts=[['typography',t],['object',m],['data',d],['icon',i]]}
  else parts=[['typography',t],['media',m],['data',d],['icon',i]];
  return parts;
 }
 function create(defOrId,config={}){const def=getDef(defOrId);if(!def)throw Error('Unknown scene family '+defOrId);const c={...defaults,...JSON.parse(JSON.stringify(def.sampleConfig||{})),...config};c.items=c.items?.length?c.items:[{label:'INPUT',value:42},{label:'MOTION',value:76},{label:'OUTPUT',value:94}];const el=document.createElement('section');el.className=`nex-scene-rig scene-${def.slug} layout-${def.renderer}`;el.dataset.componentId=def.id;el.dataset.slug=def.slug;el.dataset.variant=(c.variant||'A').toUpperCase();el.dataset.style=c.style;el.dataset.energy=c.energy;el.setAttribute('role','group');el.setAttribute('aria-label',def.accessibilityLabel);el.__sceneConfig=c;el.innerHTML=`<div class="sr-shell"><div class="sr-kicker">${esc(c.subtitle)}</div><div class="sr-direct-copy"><h2>${esc(c.title)}</h2><p>${esc(c.body)}</p></div><div class="sr-layout">${structure(def,c).map((p,idx)=>`<div class="sr-slot sr-slot-${idx+1}" data-part="${p[0]}" data-slug="${p[1]}"></div>`).join('')}</div><div class="sr-index">${String(def.order).padStart(2,'0')} · ${esc(def.name)}</div><div class="sr-grain"></div></div>`;const parts=structure(def,c);el.querySelectorAll('.sr-slot').forEach((slot,idx)=>mountPart(slot,parts[idx][0],parts[idx][1],c,def));requestAnimationFrame(()=>requestAnimationFrame(()=>fit(el)));return el}
 function fitParts(el){el.querySelectorAll('.sr-slot').forEach(slot=>{const child=slot.firstElementChild;if(!child)return;child.style.transform='';child.style.transformOrigin='center';const sw=Math.max(1,slot.clientWidth-8),sh=Math.max(1,slot.clientHeight-8),cw=Math.max(1,child.offsetWidth||child.scrollWidth),ch=Math.max(1,child.offsetHeight||child.scrollHeight),scale=Math.min(1,sw/cw,sh/ch);child.style.transform=`scale(${Math.max(.34,scale)})`;});return el}
 function fit(el){fitParts(el);el.querySelectorAll('.sr-kicker,.sr-index').forEach(n=>{let g=0;while((n.scrollWidth>n.clientWidth||n.scrollHeight>n.clientHeight)&&g++<30){let s=parseFloat(getComputedStyle(n).fontSize)||12;if(s<=7)break;n.style.fontSize=(s-.35)+'px'}});return el}
 function animate(target,config={}){const el=q(target);if(!el)throw Error('Scene target missing');const c=el.__sceneConfig||{},d=Number(config.duration||c.duration||7.5),amp={low:.72,medium:1,high:1.28}[config.energy||c.energy||'medium']||1,tl=NexMotion.createTimeline({defaults:{ease:'power3.out'}}),shell=el.querySelector('.sr-shell'),slots=[...el.querySelectorAll('.sr-slot')];tl.fromTo(shell,{opacity:0,scale:.96,rotation:-.8*amp},{opacity:1,scale:1,rotation:0,duration:d*.16,ease:'power2.out'},.12);tl.fromTo(el.querySelector('.sr-kicker'),{x:-40,opacity:0},{x:0,opacity:1,duration:d*.13,ease:'power3.out'},.22);slots.forEach((slot,idx)=>tl.fromTo(slot,{x:(idx%2?-1:1)*(40+idx*12)*amp,y:22+idx*6,opacity:0,scale:.91,rotation:(idx%2?-1:1)*2.2},{x:0,y:0,opacity:1,scale:1,rotation:0,duration:d*.2,ease:idx%2?'back.out(1.7)':'power3.out'},.35+idx*d*.055));tl.fromTo(el.querySelector('.sr-index'),{y:18,opacity:0},{y:0,opacity:1,duration:d*.12},d*.58);tl.addUpdate(d*.72,d*.26,p=>{const wave=Math.sin(p*Math.PI*2);shell.style.setProperty('--scene-breathe',String(wave*.5+.5));shell.style.transform=`translateY(${wave*1.5*amp}px)`},'none');tl.seek(0);el.__timeline=tl;return tl}
 function update(target,config={}){const el=q(target),next=create(el.dataset.componentId,{...el.__sceneConfig,...config});el.replaceWith(next);return next}
 return{registry,getDef,create,animate,update,fit,fitParts};
})();
