import os
for _k,_v in (('FLX','0.0008'),('FLZ','0.0'),('LIDW','1.2'),('LLW','0.45')): os.environ.setdefault(_k,_v)
exec(open(__import__('os').environ['PV1']+'/malerelax_pre.py').read())
exec(open(__import__('os').environ['PV1']+'/male2.py').read())
exec(open(__import__('os').environ['PV1']+'/malebrow.py').read())
exec(open(__import__('os').environ['PV1']+'/facealign.py').read())
exec(open(__import__('os').environ['PV1']+'/garm.py').read())
exec(open(__import__('os').environ['PV1']+'/modH.py').read())
exec(open(__import__('os').environ['PV1']+'/lip.py').read())
exec(open(__import__('os').environ['PV1']+'/skintone.py').read())
exec(open(__import__('os').environ['PV1']+'/haircol.py').read())
exec(open(__import__('os').environ['PV1']+'/garmall.py').read())
exec(open(__import__('os').environ['PV1']+'/facerestore.py').read())
exec(open(__import__('os').environ['PV1']+'/watch.py').read())
exec(open(__import__('os').environ['PV1']+'/malerelax.py').read())
