(()=>{
 const grid=document.querySelector('#motionGrid'),registry=NexMotion.registry;let filter='all',query='';
 const controls={style:document.querySelector('#motionStyle'),palette:document.querySelector('#motionPalette'),energy:document.querySelector('#motionEnergy'),ratio:document.querySelector('#motionRatio'),duration:document.querySelector('#motionDuration'),intensity:document.querySelector('#motionIntensity')};
 const objectIds=['object.rectangular-card.paper-01','object.sticky-note.paper-01','object.speech-bubble.paper-01'];
 function opts(def){let d=Number(controls.duration.value);if(def.subtype==='ambient')d=Math.max(2.2,d*2.7);if(def.subtype==='transition')d=Math.max(.65,Math.min(1.55,d));return {duration:d,intensity:Number(controls.intensity.value),energy:controls.energy.value}}
 function createPaper(i,def){const el=NexPaperObjects.create(objectIds[i%objectIds.length],{title:def.name,body:'The same runtime attaches to any reusable paper component.',meta:def.subtype.toUpperCase()});el.classList.add('matrix-paper');if(def.key==='numeric-count'){const n=document.createElement('strong');n.dataset.motionNumber='240';n.textContent='240';n.className='motion-counter-badge matrix-data';el.appendChild(n)}if(def.key==='connect'){const a=document.createElement('i'),b=document.createElement('i');a.dataset.connectFrom='';b.dataset.connectTo='';a.className='matrix-node a';b.className='matrix-node b';el.append(a,b)}return el}
 function createText(def){const el=document.createElement('div');el.className='matrix-text';el.dataset.motionType='text';el.dataset.motionText=def.key==='type-or-write'?'PAPER WRITES ITSELF':def.key==='numeric-count'?'1,250':'MOVE THE MESSAGE';if(def.key==='numeric-count'){el.dataset.motionNumber='1250';el.textContent='1,250'}else el.textContent=el.dataset.motionText;return el}
 function createSvg(def){const el=document.createElement('div');el.className='matrix-svg';el.dataset.motionType='svg';el.innerHTML='<svg viewBox="0 0 100 100"><path d="M18 57 L39 78 L82 25"/></svg>';if(def.key==='numeric-count'){el.innerHTML='<strong data-motion-number="96" class="matrix-data">96</strong>'}return el}
 function makeScene(style,label,variant){const scene=document.createElement('div');scene.className='transition-mini-scene';scene.dataset.sceneStyle=style;scene.innerHTML=`<i></i><strong>${label}</strong><small>${variant}</small>`;return scene}
 function createTransitionMount(def,variant){const wrap=document.createElement('div');wrap.className='transition-mini';const out=makeScene(variant,'BEFORE',def.name),inc=makeScene(variant,'AFTER',def.subtype);wrap.append(out,inc);return {wrap,out,inc}}
 function replayCard(card,def){const mounts=[...card.querySelectorAll('.motion-target-cell')];const o=opts(def);if(def.subtype==='transition'){
   mounts.forEach((cell,i)=>{cell.querySelector('.transition-mini')?.remove();const pair=createTransitionMount(def,['editorial','collage','technical'][i]);cell.appendChild(pair.wrap);const tl=NexMotion.transition(pair.out,pair.inc,def,o);pair.wrap.__tl=tl;tl.restart()});
 }else{
   mounts.forEach((cell,i)=>{cell.querySelectorAll(':scope > :not(.target-label)').forEach(x=>x.remove());const target=i===0?createPaper(i,def):i===1?createText(def):createSvg(def);cell.appendChild(target);const tl=NexMotion.apply(target,def,o);target.__tl=tl;tl.restart()});
 }}
 function render(){grid.innerHTML='';const list=registry.filter(x=>(filter==='all'||x.subtype===filter)&&(!query||[x.name,x.id,x.description,...x.keywords,...x.intents].join(' ').toLowerCase().includes(query)));document.querySelector('#motionCount').textContent=String(list.length).padStart(2,'0');list.forEach((def,index)=>{const card=document.createElement('article');card.className='motion-card';card.dataset.motionId=def.id;const labels=def.subtype==='transition'?['editorial scene','collage scene','technical scene']:['paper object','editable text','layered svg'];card.innerHTML=`<header class="motion-card-head"><div><h2>${def.name}</h2><div class="motion-id">${def.id}</div></div><span class="motion-badge">${def.subtype}</span></header><div class="motion-targets">${labels.map(x=>`<div class="motion-target-cell" data-ratio="${controls.ratio.value}"><span class="target-label">${x}</span></div>`).join('')}</div><footer class="motion-actions"><div class="motion-meta">${def.duration.recommended}s default · ${def.defaultEase}<br>${def.compatibleTargets.join(' / ')}</div><div><button class="manifest-btn">Manifest</button> <button class="replay-btn">Replay</button></div></footer>`;
   card.querySelector('.manifest-btn').onclick=()=>show(def);card.querySelector('.replay-btn').onclick=()=>replayCard(card,def);grid.appendChild(card);
   // establish valid visible end states without autoplaying all 96 examples
   const o=opts(def);if(def.subtype==='transition'){card.querySelectorAll('.motion-target-cell').forEach((cell,i)=>{const pair=createTransitionMount(def,['editorial','collage','technical'][i]);cell.appendChild(pair.wrap);const tl=NexMotion.transition(pair.out,pair.inc,def,o);pair.wrap.__tl=tl;tl.seek(tl.duration())})}else card.querySelectorAll('.motion-target-cell').forEach((cell,i)=>{const target=i===0?createPaper(index,def):i===1?createText(def):createSvg(def);cell.appendChild(target);const tl=NexMotion.apply(target,def,o);target.__tl=tl;tl.seek(tl.duration())});
 });}
 function show(def){const panel=document.querySelector('#motionManifest');panel.querySelector('pre').textContent=JSON.stringify(def,null,2);panel.classList.add('open')}
 document.querySelector('#motionManifestClose').onclick=()=>document.querySelector('#motionManifest').classList.remove('open');
 document.querySelectorAll('.motion-filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.motion-filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;render()});
 document.querySelector('#motionSearch').oninput=e=>{query=e.target.value.trim().toLowerCase();render()};controls.style.onchange=()=>NexTheme.setStyle(controls.style.value);controls.palette.onchange=()=>NexTheme.applyPalette(controls.palette.value);controls.energy.onchange=render;controls.ratio.onchange=()=>document.querySelectorAll('.motion-target-cell').forEach(x=>x.dataset.ratio=controls.ratio.value);controls.duration.oninput=()=>{document.querySelector('#durationOut').textContent=Number(controls.duration.value).toFixed(2)+'s'};controls.intensity.oninput=()=>{document.querySelector('#intensityOut').textContent=Number(controls.intensity.value).toFixed(2)+'×'};document.querySelector('#replayVisible').onclick=()=>document.querySelectorAll('.motion-card .replay-btn').forEach((b,i)=>setTimeout(()=>b.click(),i*75));
 NexTheme.setStyle(controls.style.value);NexTheme.applyPalette(controls.palette.value);render();
})();
